words: tuple[str, ...] = (
    "pizza", "tacos", "burrito", "nachos", "wings",
    "burger", "fries", "milkshake", "latte", "espresso",
    "redbull", "monster", "gatorade", "boba", "sushi",
    "donuts", "bagel", "pancakes", "waffles", "cereal",
    "popcorn", "icecream", "cheesecake", "brownie", "cookie",
    "smoothie", "pretzels", "cupcake", "muffin", "quesadilla",
    "kegstand", "beerpong", "flipcup", "formal", "mixer",
    "rush", "pledge", "initiation", "philanthropy", "homecoming",
    "springbreak", "roadtrip", "dormroom", "roommate", "mealplan",
    "dininghall", "cramming", "procrastinate", "deadline", "groupchat",
    "venmo", "spotify", "netflix", "tiktok", "instagram",
    "snapchat", "discord", "twitch", "youtube", "reddit",
    "doomscroll", "cap", "nocap", "lowkey", "highkey",
    "vibe", "slay", "ohio", "gyatt", "npc",
    "cringe", "drip", "ghosted", "simp", "flex",
    "clout", "savage", "salty", "thirsty", "extra",
    "basic", "ratio", "cooked", "delulu", "iykyk",
    "fomo", "yolo", "finsta", "situationship", "bestie",
    "yeet", "oof", "yikes", "lit", "dank",
    "epic", "noob", "poggers", "copium", "glizzy",
    "chad", "karen", "boomer", "zoomer", "malding",
    "sheeple", "bussed", "capping", "vibing", "ghosting",
    "pickleball", "spikeball", "cornhole", "discgolf", "kayaking",
    "surfing", "snowboarding", "skiing", "bowling", "darts",
    "billiards", "poker", "blackjack", "chess", "workout",
    "deadlift", "squat", "benchpress", "cardio", "yoga",
    "pilates", "crossfit", "marathon", "sprint", "dodgeball",
    "kickball", "paintball", "archery", "boxing", "karate",
    "concert", "festival", "coachella", "playlist", "karaoke",
    "guitar", "piano", "drums", "vinyl", "headphones",
    "airpods", "podcast", "sitcom", "anime", "manga",
    "cosplay", "comiccon", "cinema", "documentary", "thriller",
    "hoodie", "sweatpants", "sneakers", "charger", "sunglasses",
    "hammock", "longboard", "scooter", "bicycle", "whiteboard",
    "calculator", "notebook", "highlighter", "flashcards", "planner",
    "lanyard", "umbrella", "sunscreen", "waterbottle", "earbuds",
    "beach", "mountains", "campfire", "bonfire", "apartment",
    "frathouse", "sorority", "campus", "stadium", "arena",
    "internship", "scholarship", "resume", "linkedin", "networking",
    "careerfair", "graduation", "diploma", "alumni", "capstone",
    "apple", "orange", "banana", "coconut", "pineapple",
    "yellowjackets", "ramblinwreck", "buzz", "georgiatech", "techtower",
    "whistle", "sting", "campanile", "klaus", "clough",
    "skiles", "bobbydodd", "mccamish", "midtown", "atlanta",
    "thetaxi", "fraternity", "brotherhood", "fellowship", "worship",
    "gospel", "disciple", "prayer", "chapel", "faith",
    "grace", "bible",
    "calculus", "physics", "chemistry", "biology", "engineering",
    "algorithms", "statistics", "economics", "thermodynamics", "psychology",
    "accounting", "linguistics",
    "football", "basketball", "soccer", "baseball", "tennis",
    "swimming", "volleyball", "lacrosse", "hockey", "frisbee",
    "wrestling", "rugby", "badminton",
    "gaming", "coding", "hiking", "climbing", "painting",
    "photography", "skateboarding", "camping", "fishing", "cooking",
    "reading", "gardening",
    "chickfila", "raisingcanes", "chipotle", "mcdonalds", "wendys",
    "popeyes", "tacobell", "wafflehouse", "cookout", "zaxbys",
    "bojangles", "dominos", "starbucks", "dunkin",
    "rizz", "gigachad", "sigma", "stonks", "skibidi",
    "goated", "bussin", "sheesh", "rickroll", "based",
    "mewing", "sussy", "bruh",
    "allnighter", "midterm", "tailgate", "ramen",
)
